name: example
description: A starting point for Dart libraries or applications.
version: 0.1.1
#homepage: https://www.example.com
#author: alois <email@example.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

dependencies:
  dioc:
    path: ../dioc

dev_dependencies:
  test: 
  build_runner:
  dioc_generator:
    path: ../dioc_generator
