name: dioc
description: Inversion of control based on dependency injection through containers.
version: 0.1.1
homepage: https://github.com/aloisdeniel/dioc
author: Alo√Øs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

dependencies:

dev_dependencies:
  test: 
