name: dioc
description: Inversion of control based on dependency injection through containers.
version: 0.0.1
homepage: https://aloisdeniel.github.io/
author: Alo√Øs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  test: ^0.12.0
